
#ifndef _PARTICLE_HELPER_HLSLI
#define _PARTICLE_HELPER_HLSLI

// definition_helper had conflictions

#define k_particle_blend_mode_opaque 0
#define k_particle_blend_mode_additive 1
#define k_particle_blend_mode_multiply 2
#define k_particle_blend_mode_alpha_blend 3
#define k_particle_blend_mode_double_multiply 4
#define k_particle_blend_mode_maximum 5
#define k_particle_blend_mode_multiply_add 6
#define k_particle_blend_mode_add_src_times_dstalpha 7
#define k_particle_blend_mode_add_src_times_srcalpha 8
#define k_particle_blend_mode_inv_alpha_blend 9
#define k_particle_blend_mode_pre_multiplied_alpha 10

#endif