
#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "postprocess.fx"
#include "hud_camera_nightvision_registers.fx"
//@generate screen

LOCAL_SAMPLER_2D(depth_sampler, 0);
LOCAL_SAMPLER_2D(color_sampler, 1);
LOCAL_SAMPLER_2D(mask_sampler, 2);
LOCAL_SAMPLER_2D(depth_through_walls_sampler, 3);

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

    /*
    //
    // Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
    //
    // Parameters:
    //
    //   float4 colors[14];
    //   sampler2D depth_sampler;
    //   sampler2D depth_through_walls_sampler;
    //   float4 falloff;
    //   float4 falloff_throught_the_wall;
    //   float float_index;
    //   float4 g_exposure;
    //   sampler2D mask_sampler;
    //   float overlapping_dimming_factor[5];
    //   float4 ping;
    //   float4x4 screen_to_world;
    //   float4 zbuf_params;
    //
    //
    // Registers:
    //
    //   Name                        Reg   Size
    //   --------------------------- ----- ----
    //   g_exposure                  c0       1
    //   falloff                     c94      1
    //   screen_to_world             c95      4
    //   ping                        c99      1
    //   colors                      c100    14
    //   overlapping_dimming_factor  c114     5
    //   falloff_throught_the_wall   c120     1
    //   zbuf_params                 c121     1
    //   float_index                 c122     1
    //   depth_sampler               s0       1
    //   mask_sampler                s2       1
    //   depth_through_walls_sampler s3       1
    //
    
        ps_3_0
        def c1, 1, 0, 2, -2
        def c2, -0, -1, -2, -3
        def c3, -4, -3, -5, -6
        dcl_texcoord v0.xy
        dcl_2d s0
        dcl_2d s2
        dcl_2d s3
        texld r0, v0, s0
        rcp r0.x, r0.x
        mad r0.x, c121.x, r0.x, c121.y
        add r0.x, -r0.x, c1.x
        add r0.y, -r0.x, c1.x
        mul r1, c96, v0.y
        mad r1, v0.x, c95, r1
        mad r2, r0.y, c97, r1
        add r2, r2, c98
        rcp r0.y, r2.w
        mul r0.yzw, r0.y, r2.xxyz
        dp3 r0.y, r0.yzww, r0.yzww
        rsq r0.y, r0.y
        rcp r0.y, r0.y
        add r0.zw, -r0.y, c99.xyxy
        mul r0.y, r0.y, c94.x
        mul r0.y, r0.y, r0.y
        mul r0.y, r0.y, r0.y
        mul r0.y, r0.y, r0.y
        exp r0.y, -r0.y
        mov r2, c1
        mad_sat r2.x, c99.z, r0.z, r2.x
        mul r2.x, r2.x, r2.x
        mul r2.x, r2.x, r2.x
        frc r3.x, c122.x
        cmp r3.y, -r3.x, c1.y, c1.x
        add r3.x, -r3.x, c122.x
        cmp r3.y, c122.x, r2.y, r3.y
        add r3.x, r3.y, r3.x
        add r4, r3.x, c2
        cmp r3.yzw, -r4_abs.x, c101.xxyz, r2.y
        cmp r3.yzw, -r4_abs.y, c103.xxyz, r3
        cmp r3.yzw, -r4_abs.z, c105.xxyz, r3
        add r5, r3.x, c3.yxzw
        add r3.x, r3.x, c3.x
        cmp r3.yzw, -r5_abs.x, c107.xxyz, r3
        cmp r3.yzw, -r5_abs.y, c109.xxyz, r3
        cmp r3.yzw, -r5_abs.z, c111.xxyz, r3
        cmp r3.yzw, -r5_abs.w, c113.xxyz, r3
        mul r3.yzw, r2.x, r3
        cmp r3.yzw, r0.z, r3, c1.y
        cmp r0.z, r0.w, c1.x, c1.y
        cmp r6, -r4_abs.x, c100, r2.y
        cmp r6, -r4_abs.y, c102, r6
        cmp r6, -r4_abs.z, c104, r6
        cmp r6, -r5_abs.x, c106, r6
        cmp r6, -r5_abs.y, c108, r6
        cmp r6, -r5_abs.z, c110, r6
        cmp r5, -r5_abs.w, c112, r6
        add r3.yzw, r3, r5.xxyz
        cmp r0.w, -r4_abs.x, c114.x, r2.y
        cmp r0.w, -r4_abs.y, c115.x, r0.w
        cmp r0.w, -r4_abs.z, c116.x, r0.w
        cmp r0.w, -r4_abs.w, c117.x, r0.w
        cmp r0.w, -r3_abs.x, c118.x, r0.w
        mad r4.xy, c121.zwzw, r2.z, v0
        mov r4.zw, v0.xyyx
        texld r6, r4.xzzw, s0
        rcp r2.x, r6.x
        mad r2.x, c121.x, r2.x, c121.y
        add r2.x, -r2.x, c1.x
        mad r6.xy, c121.zwzw, r2.w, v0
        mov r6.zw, v0.xyyx
        texld r7, r6.xzzw, s0
        rcp r2.y, r7.x
        mad r2.y, c121.x, r2.y, c121.y
        add r2.x, -r2.y, r2.x
        add r2.x, r2.x, c1.x
        mad r2.x, r0.x, -c1.z, r2.x
        texld r7, r4.wyzw, s0
        rcp r2.z, r7.x
        mad r2.z, c121.x, r2.z, c121.y
        add r2.z, -r2.z, c1.x
        texld r7, r6.wyzw, s0
        rcp r2.w, r7.x
        mad r2.w, c121.x, r2.w, c121.y
        add r2.z, -r2.w, r2.z
        mad r2.z, r0.x, -c1.z, r2.z
        rcp r0.x, r0.x
        add r2.y, r2.z, c1.x
        dp2add r2.z, r2, r2, c1.y
        add r2.x, r2.y, r2.x
        rsq r2.y, r2.z
        rcp r2.y, r2.y
        mul_sat r0.x, r0.x, r2.y
        mul r2.y, r0.w, r0.x
        cmp r0.x, -r2.x, r0.x, r2.y
        mul r2.w, r5.w, c0.w
        mul r5.xyz, r5, r2.w
        texld r7, v0, s3
        rcp r3.x, r7.x
        mad r3.x, c121.x, r3.x, c121.y
        add r3.x, -r3.x, c1.x
        add r5.w, -r3.x, c1.x
        mad r1, r5.w, c97, r1
        add r1, r1, c98
        rcp r1.w, r1.w
        mul r1.xyz, r1.w, r1
        dp3 r1.x, r1, r1
        rsq r1.x, r1.x
        rcp r1.x, r1.x
        mul r1.y, r1.x, c120.x
        add r1.x, -r1.x, c120.y
        mul r1.y, r1.y, r1.y
        mul r1.y, r1.y, r1.y
        mul r1.y, r1.y, r1.y
        exp r1.y, -r1.y
        texld r7, v0, s2
        mul r1.y, r1.y, r7.x
        cmp r1.z, r1.x, c1.x, c1.y
        mul r1.y, r1.z, r1.y
        mul r5.xyz, r1.y, r5
        mad r7.yzw, r0.x, r3, r5.xxyz
        mul r0.x, r0.y, r7.x
        mul r0.x, r0.z, r0.x
        mul r8.xyz, r0.x, r7.yzww
        texld r9, r4.xzzw, s3
        texld r4, r4.wyzw, s3
        rcp r0.x, r4.x
        mad r0.x, c121.x, r0.x, c121.y
        rcp r0.y, r9.x
        mad r0.y, c121.x, r0.y, c121.y
        add r0.xy, -r0, c1.x
        texld r4, r6.xzzw, s3
        texld r6, r6.wyzw, s3
        rcp r0.z, r6.x
        mad r0.z, c121.x, r0.z, c121.y
        add r0.x, -r0.z, r0.x
        mad r0.x, r3.x, -c1.z, r0.x
        add r6.y, r0.x, c1.x
        rcp r0.x, r4.x
        mad r0.x, c121.x, r0.x, c121.y
        add r0.x, -r0.x, r0.y
        add r0.x, r0.x, c1.x
        mad r6.x, r3.x, -c1.z, r0.x
        rcp r0.x, r3.x
        dp2add r0.y, r6, r6, c1.y
        add r0.z, r6.y, r6.x
        rsq r0.y, r0.y
        rcp r0.y, r0.y
        mul_sat r0.x, r0.x, r0.y
        mul r0.y, r0.w, r0.x
        cmp r0.x, -r0.z, r0.x, r0.y
        mad r2.xyz, r0.x, r3.yzww, r5
        mul r0, r1.y, r2
        mov r8.w, c1.y
        cmp r0, r1.x, r0, r8
        cmp oC0, -r7.x, c1.y, r0
    
    // approximately 150 instruction slots used (11 texture, 139 arithmetic)
    */
}