
#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "unknown_101_unknown_102_registers.fx"
//@generate screen

LOCAL_SAMPLER_2D(color_sampler, 0);
LOCAL_SAMPLER_2D(gbuf_sampler, 1);
LOCAL_SAMPLER_2D(depth_sampler, 2);

struct unknown_102_output
{
    float4 position : SV_POSITION;
    float2 unknown_0 : TEXCOORD0;
    float3 unknown_1 : TEXCOORD1;
};

unknown_102_output default_vs(vertex_type IN)
{
    unknown_102_output OUT;

    OUT.unknown_0 = IN.texcoord;

    float2 offset = (IN.texcoord - 0.5f) * vs_ref_reflections_cam_vec_0.xy;
    OUT.unknown_1.x = offset.x;
    OUT.unknown_1.y = -offset.y;
    OUT.unknown_1.z = 1.0f;

    OUT.position.xy = IN.position;
    OUT.position.z = 0.5f;
    OUT.position.w = 1.0f;

    return OUT;
}

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

    /*
    //
    // Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
    //
    // Parameters:
    //
    //   sampler2D color_sampler;
    //   sampler2D depth_sampler;
    //   sampler2D gbuf_sampler;
    //   float4 pixel_size;
    //
    //
    // Registers:
    //
    //   Name          Reg   Size
    //   ------------- ----- ----
    //   pixel_size    c1       1
    //   color_sampler s0       1
    //   gbuf_sampler  s1       1
    //   depth_sampler s2       1
    //
    
        ps_3_0
        def c0, 1, 0, 0.333333343, 0.0500000007
        def c2, 0.5, 0, -2, 0.0901684389
        def c3, 0.0535277724, 100, 1, 0
        defi i0, 5, 0, 0, 0
        dcl_texcoord v0.xy
        dcl_2d s0
        dcl_2d s1
        dcl_2d s2
        mul r0, c0.xxyy, v0.xyxx
        texldl r1, r0, s1
        dp3 r1.x, r1, c0.z
        texldl r2, r0, s0
        if_lt c0.w, r1.x
          texldl r0, r0, s2
          rcp r0.y, r0.x
          mov r1, c0.xyyy
          mad r3.xy, c1.x, -r1, v0
          mov r3.zw, c0.y
          texldl r3, r3, s2
          rcp r0.z, r3.x
          mad r1.xy, c1.x, r1, v0
          texldl r1, r1, s2
          rcp r0.w, r1.x
          add r0.z, r0.w, r0.z
          mov r0.w, c1.y
          add r1.y, r0.w, v0.y
          add r3.y, -r0.w, v0.y
          mul r3.zw, c0.xyxy, v0.x
          texldl r3, r3.zyww, s2
          mul r1.zw, c0.xyxy, v0.x
          texldl r1, r1.zyww, s2
          rcp r0.w, r3.x
          rcp r1.x, r1.x
          add r0.w, r0.w, r1.x
          mad r0.w, r0.w, c2.x, -r0.y
          mad r0.y, r0.z, c2.x, -r0.y
          max r1.x, r0_abs.y, r0_abs.w
          mul r0.x, r0.x, r1.x
          mov r1.zw, c0.y
          mov r0.yzw, c0.y
          mov r3.xyz, c0.y
          mov r2.w, c2.z
          rep i0
            mov r4.x, r2.w
            mov r5.xyz, r0.yzww
            mov r6.xyz, r3
            mov r3.w, c2.z
            rep i0
              mov r4.y, r3.w
              mad r1.xy, c1, r4, v0
              texldl r7, r1, s0
              mul r4.yzw, r7.xxyz, r7.xxyz
              mul r1.x, r3.w, r3.w
              mad_sat r1.y, r2.w, r2.w, r1.x
              mad r1.x, -r2.w, r2.w, -r1.x
              mul r1.x, r1.x, c2.w
              exp r1.x, r1.x
              mul r1.x, r1.y, r1.x
              mad r6.xyz, r4.yzww, r1.x, r6
              mad r5.xyz, r7, r1.x, r5
              add r3.w, r3.w, c0.x
            endrep
            mov r0.yzw, r5.xxyz
            mov r3.xyz, r6
            add r2.w, r2.w, c0.x
          endrep
          mul r1.xyz, r0.yzww, c3.x
          mul r1.xyz, r1, r1
          mad r1.xyz, r3, c3.x, -r1
          rcp r3.x, r1.x
          rcp r3.y, r1.y
          rcp r3.z, r1.z
          mad r1.xyz, r0.yzww, -c3.x, r2
          mul r1.xyz, r1, r1
          mul r1.xyz, r3, r1
          max r2.w, r1.y, r1.z
          max r3.x, r1.x, r2.w
          add_sat r1.x, r3.x, -c0.x
          mad r0.yzw, r0, c3.x, -r2.xxyz
          mad oC0.xyz, r1.x, r0.yzww, r2
          mad_sat oC0.w, r0.x, -c3.y, c3.z
        else
          mov oC0.xyz, r2
          mov oC0.w, c0.y
        endif
    
    // approximately 93 instruction slots used (16 texture, 77 arithmetic)
    */
}