
#define POSTPROCESS_USE_CUSTOM_VERTEX_SHADER

#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "postprocess.fx"
#include "unknown_101_unknown_102_registers.fx"
//@generate screen

LOCAL_SAMPLER_2D(color_sampler, 0);

screen_output default_vs(screen_output IN)
{
	screen_output OUT;
	OUT.texcoord=		IN.texcoord;
	OUT.position.xy=	IN.position;
	OUT.position.z=     0.5f;
	OUT.position.w=     1.0f;
	return OUT;
}

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

	/*
	//
	// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
	//
	// Parameters:
	//
	//   sampler2D color_sampler;
	//   float4 pixel_size;
	//   float4 ps_reg_blur_dir;
	//
	//
	// Registers:
	//
	//   Name            Reg   Size
	//   --------------- ----- ----
	//   pixel_size      c1       1
	//   ps_reg_blur_dir c3       1
	//   color_sampler   s0       1
	//
	
	    ps_3_0
	    def c0, 1, 0, 0, -0.180336878
	    defi i0, 4, 0, 0, 0
	    dcl_texcoord v0.xy
	    dcl_2d s0
	    mul r0, c0.xxyy, v0.xyxx
	    texldl r0, r0, s0
	    mov r1.zw, c0.y
	    mov r2.xyz, r0
	    mov r2.w, c0.x
	    mov r3.xy, c0.x
	    rep i0
	      mad r3.zw, r3.y, c3.xyxy, c3
	      mad r1.xy, c1, r3.zwzw, v0
	      texldl r4, r1, s0
	      mul r3.x, r3.x, r4.w
	      mul r1.x, r3.y, r3.y
	      mul r1.x, r1.x, c0.w
	      exp r1.x, r1.x
	      mul r1.y, r3.x, r1.x
	      mad r2.xyz, r4, r1.y, r2
	      mad r2.w, r1.x, r3.x, r2.w
	      add r3.y, r3.y, c0.x
	    endrep
	    mov r1.zw, c0.y
	    mov r0.xyz, r2
	    mov r3.x, r2.w
	    mov r3.yz, c0.x
	    rep i0
	      mad r4.xy, -r3.z, c3, c3.zwzw
	      mad r1.xy, c1, r4, v0
	      texldl r4, r1, s0
	      mul r3.y, r3.y, r4.w
	      mul r1.x, r3.z, r3.z
	      mul r1.x, r1.x, c0.w
	      exp r1.x, r1.x
	      mul r1.y, r3.y, r1.x
	      mad r0.xyz, r4, r1.y, r0
	      mad r3.x, r1.x, r3.y, r3.x
	      add r3.z, r3.z, c0.x
	    endrep
	    rcp r1.x, r3.x
	    mul oC0.xyz, r0, r1.x
	    mov oC0.w, r0.w
	
	// approximately 48 instruction slots used (6 texture, 42 arithmetic)
	*/
}