
#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "unknown_101_unknown_102_registers.fx"
//@generate screen

LOCAL_SAMPLER_2D(color_sampler, 0);
LOCAL_SAMPLER_2D(depth_sampler, 2);
LOCAL_SAMPLER_2D(normal_sampler, 3);
LOCAL_SAMPLER_2D(gbuf_sampler, 4);
LOCAL_SAMPLER_2D(depth_half_max_sampler, 5);

struct unknown_101_output
{
    float4 position : SV_POSITION;
    float4 unknown_0 : TEXCOORD0;
    float3 unknown_1 : TEXCOORD1;
};

unknown_101_output default_vs(vertex_type IN)
{
    unknown_101_output OUT;

    OUT.unknown_0.xy = IN.texcoord;
    OUT.unknown_0.zw = IN.texcoord * vs_reg_uv_scale_offset.xy + vs_reg_uv_scale_offset.zw;

    float2 offset = (IN.texcoord - 0.5f) * vs_ref_reflections_cam_vec_0.xy;
    OUT.unknown_1.x = offset.x;
    OUT.unknown_1.y = -offset.y;
    OUT.unknown_1.z = 1.0f;

    OUT.position.xy = IN.position;
    OUT.position.z = 0.5f;
    OUT.position.w = 1.0f;

    return OUT;
}

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

    /*
    //
    // Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
    //
    // Parameters:
    //
    //   sampler2D color_sampler;
    //   sampler2D depth_half_max_sampler;
    //   sampler2D depth_sampler;
    //   sampler2D gbuf_sampler;
    //   sampler2D normal_sampler;
    //   float4 pixel_size;
    //   float4 ps_reg_reflections_cam_vec_1;
    //   float4 ps_reg_reflections_matrview_0;
    //   float4 ps_reg_reflections_matrview_1;
    //   float4 ps_reg_reflections_matrview_2;
    //   float4 ps_reg_reflections_params2_0;
    //   float4 ps_reg_reflections_params_0;
    //
    //
    // Registers:
    //
    //   Name                          Reg   Size
    //   ----------------------------- ----- ----
    //   pixel_size                    c1       1
    //   ps_reg_reflections_cam_vec_1  c4       1
    //   ps_reg_reflections_params2_0  c5       1
    //   ps_reg_reflections_matrview_0 c6       1
    //   ps_reg_reflections_matrview_1 c7       1
    //   ps_reg_reflections_matrview_2 c8       1
    //   ps_reg_reflections_params_0   c9       1
    //   color_sampler                 s0       1
    //   depth_sampler                 s2       1
    //   normal_sampler                s3       1
    //   gbuf_sampler                  s4       1
    //   depth_half_max_sampler        s5       1
    //
    
        ps_3_0
        def c0, 0.300000012, 0, 50, 0.0500000007
        def c2, 0.333333343, 2, -1, 0.100000001
        def c3, 0.03125, 0.00100000005, 0.5, -0.5
        def c10, 0.5, -0.5, 1, 15
        def c11, -6.66666674e-005, 6.66666674e-005, 0, 1
        def c12, 0.150000006, 0, 0, 0
        def c13, 0, 1000, 1, 12
        defi i0, 15, 0, 0, 0
        defi i1, 4, 0, 0, 0
        dcl_texcoord v0.xy
        dcl_texcoord1 v1.xyz
        dcl_2d s0
        dcl_2d s2
        dcl_2d s3
        dcl_2d s4
        dcl_2d s5
        mov r0.xzw, c0.xyyy
        mad r0.xy, c1, r0.x, v0
        texldl r1, r0.xyww, s2
        add r1.y, -r1.x, c0.z
        mul_sat r1.y, r1.y, c0.w
        texldl r2, r0.xyww, s4
        mul r1.yzw, r1.y, r2.xxyz
        dp3 r1.y, r1.yzww, c2.x
        if_lt c0.w, r1.y
          texldl r0, r0, s3
          mad r0.xyz, r0, c2.y, c2.z
          nrm r2.xyz, r0
          dp3 r0.x, r2, c8
          mov r0.z, -r0.x
          dp3 r0.w, r2, c6
          mov r0.x, -r0.w
          dp3 r0.y, r2, c7
          nrm r2.xyz, v1
          dp3 r0.w, r2, r0
          add r0.w, r0.w, r0.w
          mad r0.xyz, r0, -r0.w, r2
          nrm r2.xyz, r0
          mov r0.w, c2.w
          mul r0.xyz, r1.x, v1
          mul r1.yzw, r0.xzzw, r2.xxyz
          mul r2.xy, r0, r1.w
          mad r1.yz, r1, r0.w, -r2.xxyw
          mul r1.yz, r1, c4.xzww
          mad r0.w, v1.z, r1.x, r1.w
          mul r1.x, r0.w, r0.z
          rcp r1.x, r1.x
          mul r1.xy, r1.x, r1.yzzw
          rcp r0.w, r0.w
          rcp r0.z, r0.z
          mul r1.w, r0.z, -r1.w
          mul r1.z, r0.w, r1.w
          rcp r2.x, c1.x
          rcp r2.y, c1.y
          mul r2.xy, r1, r2
          dp2add r0.w, r2, r2, c0.y
          rsq r0.w, r0.w
          rcp r0.w, r0.w
          mad r0.w, r0.w, c3.x, c3.y
          rcp r0.w, r0.w
          mul r1.xyz, r0.w, r1
          mul r1.xyz, r1, c5.x
          mul r0.xy, r0.z, r0
          mul r0.xy, r0, c4.zwzw
          mad r0.xy, r0, c3.zwzw, c3.z
          rcp r0.w, r1.z
          mul r2.xyz, r1, c10
          mul r2.xyz, r0.w, r2
          mov r3.w, c0.y
          mov r4.w, c0.y
          mov r5.zw, c0.y
          mov r3.xyz, r0
          mov r6.xyz, r0
          mov r7.xyz, c0.y
          mov r0.w, c2.z
          mov r1.w, -c2.z
          mov r2.w, c0.y
          mov r6.w, c0.y
          rep i0
            mad r8.xyz, r1, c10, r3
            add r7.w, -r8.z, c11.y
            max r8.w, r7.w, c0.y
            mad r3.xyz, r2, r8.w, r8
            add r7.w, r8.z, c11.x
            cmp r2.w, r7.w, r2.w, -c2.z
            texldl r8, r3.xyww, s5
            rcp r7.w, r8.x
            add r7.w, -r3.z, r7.w
            cmp r8.x, -r7.w, c11.z, c11.w
            cmp r8.x, r0.w, c0.y, r8.x
            if_ne r8.x, -r8.x
              mov r8.xyz, r6
              mov r5.xy, r3
              mov r9.x, r3.z
              mov r9.y, r7.w
              mov r8.w, c3.z
              mov r9.z, -c2.z
              rep i1
                mov r10.yz, r9
                mov r11.z, r9.x
                mov r10.x, r11.z
                mov r11.xy, r5
                add r11.xyz, r8, r11
                mul r4.xyz, r11, c3.z
                texldl r12, r4.xyww, s2
                rcp r9.w, r12.x
                mad r11.y, r11.z, -c3.z, r9.w
                cmp r5.xy, -r11.y, r5, r4
                mov r11.x, r4.z
                add r11.z, -r8.w, r9.z
                cmp r9.xyz, -r11.y, r10, r11
                cmp r8.xyz, -r11.y, r4, r8
                mul r8.w, r8.w, c3.z
              endrep
              add r4.x, -r1_abs.z, r9.y
              texldl r8, r5, s0
              mad_sat r4.x, r4.x, -c13.y, c13.z
              mul r4.yz, r5.xxyw, c13.w
              add r9.xw, -r5.xyzy, -c2.z
              mad_sat r4.yz, r4, r9.xxww, c3.z
              mul r4.y, r4.z, r4.y
              mul r4.y, r4.y, r4.y
              mul r4.x, r4.y, r4.x
              add r4.y, -r6.w, c10.w
              add r4.y, -r9.z, r4.y
              mul_sat r4.y, r4.y, c12.x
              mul r4.y, r4.y, r4.y
              mul r4.x, r4.y, r4.x
              min r8.w, r1.w, r4.x
              mad r4.xyz, r8, r8.w, r7
              add r8.x, r1.w, -r8.w
              max r1.w, r8.x, c0.y
            else
              mov r4.xyz, r7
            endif
            if_ne r2.w, -r2.w
              mov r7.xyz, r4
              break_ne -c2.z, -c2.z
            endif
            add r6.w, r6.w, -c2.z
            mov r6.xyz, r3
            mov r0.w, r7.w
            mov r7.xyz, r4
          endrep
          mul r0.xyz, r7, c9.x
        else
          mov r0.xyz, c0.y
        endif
        mov oC0.xyz, r0
        mov oC0.w, c0.y
    
    // approximately 161 instruction slots used (12 texture, 149 arithmetic)
    */
}