
#define POSTPROCESS_USE_CUSTOM_VERTEX_SHADER

#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "postprocess.fx"
//@generate screen

LOCAL_SAMPLER_2D(depth_sampler, 0);

screen_output default_vs(screen_output IN)
{
	screen_output OUT;
	OUT.texcoord=		IN.texcoord;
	OUT.position.xy=	IN.position;
	OUT.position.z=     0.5f;
	OUT.position.w=     1.0f;
	return OUT;
}

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

	/*
	//
	// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
	//
	// Parameters:
	//
	//   sampler2D depth_sampler;
	//   float4 pixel_size;
	//
	//
	// Registers:
	//
	//   Name          Reg   Size
	//   ------------- ----- ----
	//   pixel_size    c1       1
	//   depth_sampler s0       1
	//
	
	    ps_3_0
	    def c0, 1, 0, 0.5, 10
	    dcl_texcoord v0.xy
	    dcl_2d s0
	    mul r0.zw, c0.xyxy, v0.x
	    mov r0.x, c1.y
	    add r0.y, -r0.x, v0.y
	    add r1.y, r0.x, v0.y
	    texldl r0, r0.zyww, s0
	    rcp r0.x, r0.x
	    mul r1.zw, c0.xyxy, v0.x
	    texldl r1, r1.zyww, s0
	    rcp r0.y, r1.x
	    add r0.x, r0.x, r0.y
	    mul r1, c0.xxyy, v0.xyxx
	    texldl r1, r1, s0
	    rcp r0.y, r1.x
	    mad r0.x, r0.x, c0.z, -r0.y
	    mov r2, c0.xyyy
	    mad r3.xy, c1.x, -r2, v0
	    mov r3.zw, c0.y
	    texldl r3, r3, s0
	    rcp r0.z, r3.x
	    mad r2.xy, c1.x, r2, v0
	    texldl r2, r2, s0
	    rcp r0.w, r2.x
	    add r0.z, r0.w, r0.z
	    mad r0.y, r0.z, c0.z, -r0.y
	    max r1.y, r0_abs.y, r0_abs.x
	    mul r0.x, r1.x, r1.y
	    mul oC0, r0.x, c0.w
	
	// approximately 32 instruction slots used (10 texture, 22 arithmetic)
	*/
}