
#define POSTPROCESS_USE_CUSTOM_VERTEX_SHADER

#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "postprocess.fx"
#include "unknown_103_unknown_104_registers.fx"
//@generate screen

LOCAL_SAMPLER_2D(depthBuf, 0);
LOCAL_SAMPLER_2D(normBuf, 1);

screen_output default_vs(screen_output IN)
{
	screen_output OUT;
	OUT.texcoord=		IN.texcoord * uv_scale_offset.xy + uv_scale_offset.zw;
	OUT.position.xy=	IN.position;
	OUT.position.zw=    1.0f;
	return OUT;
}

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

	/*
	//
	// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
	//
	// Parameters:
	//
	//   sampler2D depthBuf;
	//   sampler2D normBuf;
	//   float4 pixel_size;
	//
	//
	// Registers:
	//
	//   Name         Reg   Size
	//   ------------ ----- ----
	//   pixel_size   c1       1
	//   depthBuf     s0       1
	//   normBuf      s1       1
	//
	
	    ps_3_0
	    def c0, -0.5, 0.5, 1, 0
	    def c2, 2, 3, 10, -1
	    def c3, 2, -4, 0, 0
	    dcl_texcoord v0.xy
	    dcl_2d s0
	    dcl_2d s1
	    mov r0.xy, c0
	    mad r1, c1.xyxy, r0.xxyx, v0.xyxy
	    mul r2, r1.xyxx, c0.zzww
	    mul r1, r1.zwxx, c0.zzww
	    texldl r1, r1, s0
	    texldl r2, r2, s0
	    mad r3, c1.xyxy, r0.xyyy, v0.xyxy
	    mul r4, r3.xyxx, c0.zzww
	    mul r3, r3.zwxx, c0.zzww
	    texldl r3, r3, s0
	    texldl r4, r4, s0
	    add r0.z, -r2.x, r4.x
	    mov r3.y, r4.x
	    max r0.w, r2.x, r4.x
	    mov r3.w, r2.x
	    mov r3.z, r1.x
	    cmp r2, r0.z, r3.yxwz, r3.wzyx
	    add r1.y, -r1.x, r3.x
	    max r4.x, r1.x, r3.x
	    add r0.w, -r0.w, r4.x
	    cmp r3, r1.y, r3, r3.zwxy
	    cmp r2, r0.w, r3, r2
	    rcp r1.x, r2.w
	    rcp r1.z, r2.x
	    mad r1.x, r1.z, c2.x, -r1.x
	    mul r3, r0.xxyx, c1.xyxy
	    mul r4, r0.xyyy, c1.xyxy
	    cmp r0.xy, r0.z, r4, r3
	    cmp r1.yw, r1.y, r4.xzzw, r3.xzzw
	    cmp r0.xy, r0.w, r1.ywzw, r0
	    mad r3.xy, r0, c2.y, v0
	    mov r3.zw, c0.w
	    texldl r3, r3, s0
	    rcp r1.y, r3.x
	    add r1.x, -r1.y, r1.x
	    mul r1.x, r2.x, r1_abs.x
	    mul_sat r1.x, r1.x, c2.z
	    mad r1.xy, r1.x, -r0, r0
	    mul r0.zw, r0.xyxy, c2.y
	    add r3.xy, r0.zyzw, v0
	    add r4.xy, r0.xwzw, v0
	    add r0.xy, r0, v0
	    mov r3.zw, c0.w
	    texldl r3, r3, s0
	    rcp r0.z, r3.x
	    rcp r0.w, r2.y
	    mad r0.w, r1.z, c2.x, -r0.w
	    add r0.z, -r0.z, r0.w
	    mul r0.z, r2.x, r0_abs.z
	    mul_sat r0.z, r0.z, c2.z
	    mad r3.x, r0.z, -r1.x, r1.x
	    mov r4.zw, c0.w
	    texldl r4, r4, s0
	    rcp r0.z, r4.x
	    rcp r0.w, r2.z
	    mad r0.w, r1.z, c2.x, -r0.w
	    add r0.z, -r0.z, r0.w
	    mul r0.z, r2.x, r0_abs.z
	    mov oC0, r2.x
	    mul_sat r0.z, r0.z, c2.z
	    mad r3.y, r0.z, -r1.y, r1.y
	    add r1.xy, r0, -r3
	    mov r1.zw, c0.w
	    texldl r1, r1, s1
	    mad r2.xy, r3, c2.y, r0
	    mov r2.zw, c0.w
	    texldl r2, r2, s1
	    add r1, r1, r2
	    mad r2.xy, r3, c2.ywzw, r0
	    mad r0.xy, r3, c2.wyzw, r0
	    mov r2.zw, c0.w
	    texldl r2, r2, s1
	    add r1, r1, r2
	    mov r0.zw, c0.w
	    texldl r0, r0, s1
	    add r0, r0, r1
	    mad r0.xyz, r0, c3.x, c3.y
	    mov oC1.w, r0.w
	    nrm r1.xyz, r0
	    mad oC1.xyz, r1, c0.y, c0.y
	
	// approximately 93 instruction slots used (22 texture, 71 arithmetic)
	*/
}