
#define POSTPROCESS_USE_CUSTOM_VERTEX_SHADER

#include "global.fx"
#include "hlsl_vertex_types.fx"
#include "utilities.fx"
#include "postprocess.fx"
//@generate screen

LOCAL_SAMPLER_2D(ssaoBuf, 0);
LOCAL_SAMPLER_2D(depthBuf, 1);
LOCAL_SAMPLER_2D(depthHalfBuf, 2);

screen_output default_vs(screen_output IN)
{
	screen_output OUT;
	OUT.texcoord=		IN.texcoord;
	OUT.position.xy=	IN.position;
	OUT.position.z=     0.5f;
	OUT.position.w=	    1.0f;
	return OUT;
}

float4 default_ps(vertex_type IN) : SV_Target
{
    return float4(1, 0, 0, 0);

	/*
	//
	// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
	//
	// Parameters:
	//
	//   sampler2D depthBuf;
	//   sampler2D depthHalfBuf;
	//   float4 pixel_size;
	//   sampler2D ssaoBuf;
	//
	//
	// Registers:
	//
	//   Name         Reg   Size
	//   ------------ ----- ----
	//   pixel_size   c1       1
	//   ssaoBuf      s0       1
	//   depthBuf     s1       1
	//   depthHalfBuf s2       1
	//
	
	    ps_3_0
	    def c0, 0.5, 1, 0, 0.0078125
	    dcl_texcoord v0.xy
	    dcl_2d s0
	    dcl_2d s1
	    dcl_2d s2
	    mov r0.x, c0.x
	    mad r0.yz, c1.xxyw, -r0.x, v0.xxyw
	    rcp r1.x, c1.x
	    rcp r1.y, c1.y
	    mul r0.yz, r0, r1.xxyw
	    frc r1.zw, r0.xyyz
	    add r0.yz, r0, -r1.xzww
	    mul r0.xw, r0.x, c1.xyzy
	    mad r0.xy, r0.yzzw, c1, r0.xwzw
	    mov r0.z, c0.z
	    texldl r2, r0.xyzz, s2
	    rcp r1.z, r2.x
	    mul r2, c0.yyzz, v0.xyxx
	    texldl r2, r2, s1
	    rcp r1.w, r2.x
	    add r2.y, -r1.z, r1.w
	    abs r3.z, r2.y
	    mov r4.zw, r0.xyyz
	    add r4.xy, r0, c1
	    texldl r5, r4.xzww, s2
	    rcp r2.y, r5.x
	    add r2.z, r1.w, -r2.y
	    abs r5.z, r2.z
	    add r2.z, -r3.z, r5.z
	    mov r3.x, r0.x
	    mov r5.x, r4.x
	    cmp r3.xz, r2.z, r3, r5
	    mov r0.w, r4.y
	    texldl r5, r0.xwzz, s2
	    mov r6.xy, r0.xwzw
	    add r0.xy, -r0, v0
	    mul r0.xy, r1, r0
	    rcp r0.z, r5.x
	    add r0.w, -r0.z, r1.w
	    lrp r2.z, r0.y, r0.z, r1.z
	    abs r6.z, r0.w
	    add r0.z, -r3.z, r6.z
	    mov r3.y, r4.z
	    texldl r5, r4.xyww, s2
	    rcp r0.w, r5.x
	    cmp r1.xyz, r0.z, r3, r6
	    add r0.z, -r0.w, r1.w
	    lrp r1.w, r0.y, r0.w, r2.y
	    lrp r3.x, r0.x, r1.w, r2.z
	    mad r0.x, r3.x, -r2.x, c0.y
	    add r0.x, -r0_abs.x, c0.w
	    add r0.y, -r1.z, r0_abs.z
	    cmp r0.yz, r0.y, r1.xxyw, r4.xxyw
	    cmp r0.xy, r0.x, v0, r0.yzzw
	    mov r0.zw, c0.z
	    texldl_pp r0, r0, s0
	    mov_pp oC0, r0.x
	
	// approximately 58 instruction slots used (12 texture, 46 arithmetic)
	*/
}